logo: # add logo name
title: Oh My Nails, Kochi
description: > # this means to ignore newlines until "baseurl:"
  Nail Art, Kochi, Custom design
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "ohmynails.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Polish Me Pefect # add banner title
banner-desc: Custom Nail Art Cafe # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Indu  # your name
about-author: # about author
email: polishmeperfectkochi@gmail.com # your email
phone: (496)-169-6557 # your pnone number
website: https://ohmynails.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: https://polishmeperfect.us18.list-manage.com/subscribe?u=4425d37d42bc4c43c51ee8def&id=d988e70c4c

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
